#!/bin/bash
# HTTP 헤더 출력 (명시적 CRLF 사용)
printf "HTTP/1.1 200 OK\r\n"
printf "Content-type: text/html\r\n"
printf "\r\n"
# HTML 시작
printf "<html>\n"
printf "	<head><title>Simple CGI Test</title></head>\n"
printf "	<body>\n"
# style.css
printf "    <style>"
printf "        body {\n"
printf "            background-color: #121212;\n"
printf "            color: #e0e0e0;\n"
printf "            font-family: Arial, sans-serif;\n"
printf "            display: flex;\n"
printf "            justify-content: center;\n"
printf "            align-items: center;\n"
printf "            height: 100vh;\n"
printf "            margin: 0;\n"
printf "        }\n"
printf "        .user-container {\n"
printf "            background-color: #1E1E1E;\n"
printf "            border-radius: 12px;\n"
printf "            width: 350px;\n"
printf "            max-height: 500px;\n"
printf "            overflow-y: auto;\n"
printf "            text-align: center;\n"
printf "            box-shadow: 0 4px 6px rgba(0,0,0,0.1);\n"
printf "        }\n"
printf "        .user-header {\n"
printf "            background-color: #2C2C2C;\n"
printf "            padding: 15px;\n"
printf "            text-align: center;\n"
printf "            border-top-left-radius: 12px;\n"
printf "            border-top-right-radius: 12px;\n"
printf "            align-items: center;\n"
printf "        }\n"
printf "        .user-list {\n"
printf "            list-style-type: none;\n"
printf "            padding: 0;\n"
printf "            margin: 0;\n"
printf "        }\n"
printf "        .user-item {\n"
printf "            display: flex;\n"
printf "            flex-direction: column;\n"
printf "            align-items: center;\n"
printf "            padding: 12px 15px;\n"
printf "            border-bottom: 1px solid #333;\n"
printf "            color: #0056b3;\n"
printf "            font-weight: 600;\n"
printf "        }\n"
printf "        #userCount {\n"
printf "            color: #F44336;\n"
printf "        }\n"
printf "        #result {\n"
printf "            color: white;\n"
printf "            font-weight: 300;\n"
printf "        }\n"
printf "    </style>\n"
# 현재 시간 표시
printf "        <div class=\"user-container\">\n"
printf "            <div class=\"user-header\">\n"
printf "		        <h2 id="cgi-header">Bash CGI Script</h2>\n"
printf "		    <div id=\"userCount\">Current time: $(date)</div>\n"
printf "            </div>\n"
# 환경변수 표시
# printf "		    <h2>Environment Variables</h2>\n"
printf "		    <ul class=\"user-list\" id=\"userList\">\n"
printf "		        <li class=\"user-item\">\n"
printf "                    <p>QUERY_STRING</p>\n"
printf "		    	    <p id="result">$QUERY_STRING</p>\n"
printf "		        </li>\n"
printf "		        <li class=\"user-item\">\n"
printf "                    <p>REQUEST_METHOD</p>\n"
printf "	    		    <p id="result">$REQUEST_METHOD</p>\n"
printf "		        </li>\n"
printf "	    	    <li class=\"user-item\">\n"
printf "                    <p>HTTP_COOKIE</p>\n"
printf "	    		    <p id="result">$HTTP_COOKIE</p>\n"
printf "	    	    </li>\n"
printf "		</ul>\n"
# HTML 종료
printf "        </div>\n"
printf "	</body>\n"
printf "</html>\n"