# Generated by Django 5.1.5 on 2025-01-19 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_remove_friendblocked_block_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendblocked',
            unique_together={('user', 'blocked_user')},
        ),
    ]
