# Generated by Django 5.1.5 on 2025-01-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_alter_friendblocked_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendblocked',
            name='casual_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friendblocked',
            name='casual_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friendblocked',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friendblocked',
            name='rating',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='friendblocked',
            name='top_rating',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='friendblocked',
            name='tournament_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friendblocked',
            name='tournament_win',
            field=models.IntegerField(default=0),
        ),
    ]
