# Generated by Django 5.1.5 on 2025-01-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_friendblocked_casual_lose_friendblocked_casual_win_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendblocked',
            name='casual_lose',
        ),
        migrations.RemoveField(
            model_name='friendblocked',
            name='casual_win',
        ),
        migrations.RemoveField(
            model_name='friendblocked',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='friendblocked',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='friendblocked',
            name='top_rating',
        ),
        migrations.RemoveField(
            model_name='friendblocked',
            name='tournament_lose',
        ),
        migrations.RemoveField(
            model_name='friendblocked',
            name='tournament_win',
        ),
    ]
