# Generated by Django 5.1.5 on 2025-01-26 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_people', models.IntegerField(default=0)),
                ('max_people', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('ONGOING', '진행중'), ('COMPLETED', '완료'), ('CANECELLED', '취소됨')], default='PENDING', max_length=20)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('match_number', models.IntegerField()),
                ('score', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('ONGOING', '진행중'), ('COMPLETED', '완료'), ('CANECELLED', '취소됨')], default='PENDING', max_length=20)),
                ('player1_before_rating', models.IntegerField()),
                ('player1_after_rating', models.IntegerField()),
                ('player2_before_rating', models.IntegerField()),
                ('player2_after_rating', models.IntegerField()),
                ('match_date', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('casual', '캐쥬얼'), ('tournament', '토너먼트'), ('ai', 'ai')], max_length=20)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_losses', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player1_matches', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player2_matches', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.tournament')),
            ],
            options={
                'ordering': ['round_number', 'match_number'],
                'unique_together': {('tournament', 'round_number', 'match_number')},
            },
        ),
    ]
