# Generated by Django 5.1.5 on 2025-01-26 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_losses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_after_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1_before_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_after_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_before_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
