# Generated by Django 5.1.5 on 2025-01-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_match_score_match_player1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
