# Generated by Django 5.1.5 on 2025-02-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_match_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['match_date']},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('casual', '캐쥬얼'), ('tournament-R1', '토너먼트-R1'), ('tournament-R2', '토너먼트-R2')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='match',
            name='match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_number',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_number',
        ),
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
