# Generated by Django 5.1.5 on 2025-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_match_options_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('casual', '캐쥬얼'), ('r1', '토너먼트-R1'), ('r2', '토너먼트-R2')], max_length=20),
        ),
    ]
