# Generated by Django 5.1.4 on 2025-01-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_image_profile_lose_count_profile_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user',
        ),
        migrations.DeleteModel(
            name='Blocked',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
