# Generated by Django 5.1.4 on 2025-01-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_mfa_secret_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mfa_secret_key',
            new_name='secret_key',
        ),
    ]
