# Generated by Django 5.1.4 on 2025-01-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_mfa_secret_key_profile_secret_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='secret_key',
            new_name='totp_secret',
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
