# Generated by Django 5.1.5 on 2025-01-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_image_profile_profile_image'),
        ('accounts', '0007_rename_secret_key_profile_totp_secret_and_more'),
    ]

    operations = [
    ]
