# Generated by Django 5.1.5 on 2025-01-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20250115_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lose_count',
            new_name='casual_lose',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='win_count',
            new_name='casual_win',
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='profile',
            name='top_rating',
            field=models.IntegerField(default=800),
        ),
        migrations.AddField(
            model_name='profile',
            name='tournament_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tournament_win',
            field=models.IntegerField(default=0),
        ),
    ]
