# Generated by Django 5.1.5 on 2025-01-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_20250115_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='totp_enabled',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='totp_secret',
        ),
    ]
