# Generated by Django 5.1.5 on 2025-01-16 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_totp_enabled_and_more'),
        ('accounts', '0009_rename_lose_count_profile_casual_lose_and_more'),
    ]

    operations = [
    ]
