# Generated by Django 5.1.5 on 2025-01-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20250116_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
