# Generated by Django 5.1.5 on 2025-01-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mode',
            field=models.CharField(blank=True, default='Casual Mod', max_length=20, null=True),
        ),
    ]
