# Generated by Django 5.1.5 on 2025-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
