# Generated by Django 5.1.5 on 2025-02-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_profile_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_logins',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='winning',
            field=models.IntegerField(default=0),
        ),
    ]
