# Generated by Django 5.1.5 on 2025-01-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totp',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
