# Generated by Django 5.1.5 on 2025-01-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='state',
            field=models.CharField(default='find', max_length=50),
            preserve_default=False,
        ),
    ]
