# Generated by Django 5.1.5 on 2025-01-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_matching_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
